version: '3'

volumes:
  reservas_local_postgres_data: {}
  reservas_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: reservas_local_django
    container_name: reservas_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: reservas_production_postgres
    container_name: reservas_local_postgres
    volumes:
      - reservas_local_postgres_data:/var/lib/postgresql/data:Z
      - reservas_local_postgres_data_backups:/backups:z
    ports:
      - "5432:5432"
    env_file:
      - ./.envs/.local/.postgres

  # docs:
  #   image: reservas_local_docs
  #   container_name: reservas_local_docs
  #   platform: linux/x86_64
  #   build:
  #     context: .
  #     dockerfile: ./compose/local/docs/Dockerfile
  #   env_file:
  #     - ./.envs/.local/.django
  #   volumes:
  #     - ./docs:/docs:z
  #     - ./config:/app/config:z
  #     - ./reservas:/app/reservas:z
  #   ports:
  #     - "9000:9000"
  #   command: /start-docs
