# Generated by Django 3.2.12 on 2022-03-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.PositiveSmallIntegerField(default=1, help_text='Piso de la habitacion'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, help_text='Numero de habitacion'),
        ),
    ]
