# Generated by Django 3.2.12 on 2022-03-23 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        ('bookings', '0002_auto_20220323_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='rooms.room'),
            preserve_default=False,
        ),
    ]
