# Generated by Django 3.2.12 on 2022-03-24 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20220323_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='state',
            field=models.ForeignKey(blank=True, default='PEN', null=True, on_delete=django.db.models.deletion.PROTECT, to='bookings.state'),
        ),
    ]
